### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by pitt59159** [ElonBrown/install-macOS#1]
根据https://03k.org/vmware-macos.html
这个教程安装，虚拟机开机后是黑屏状态

**Comment by Phil2ng** [comment]
这应该是个别问题，具体原因清楚

**Comment by pitt59159** [comment]
确实不是镜像问题，我升级vm之后所有虚拟机的系统都启动不了，是由于LSP导致的界面黑屏。
管理员登录cmd执行netsh winsock reset 解决了这个情况。
后面成功安装了。
